# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Category',
            new_name='category',
        ),
    ]
